[package]
name = "rhlk"
version = "0.1.0"
edition = "2021"

[lib]
name = "rhlk"
path = "src/lib.rs"

[[bin]]
name = "rhlk"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2"

[dev-dependencies]
pretty_assertions = "1"
